title: "NoOoOoOoOoMan"
email: nomanrobotics@hotmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: nomanrobotics
paginate: 30
#disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: GTM-T3572P62

# Authors
authors:
  nomanrobotics:
    name: nomanrobotics
    display_name: Noman Robotics
    avatar: 'assets/images/sal.png'
    email: nomanrobotics@hotmail.com
    description: "Author of Noman Robotics Website."
  

# Social
social:
  github: https://github.com/NoManRobotics
  bilibili: https://space.bilibili.com/3546858276259913?spm_id_from=333.1007.0.0
  xiaohongshu: https://www.xiaohongshu.com/user/profile/5ed2695f00000000010037d6
  taobao: https://item.taobao.com/item.htm?abbucket=16&id=981025990160&mi_id=0000lamy9ADYHWJVrEwnQ_xJJvEiFLaFc77ctoYvorl1DTo&ns=1&priceTId=2147884517619198641492303e0e6a&skuId=6105375190479&spm=a21n57.1.hoverItem.2&utparam=%7B%22aplus_abtest%22%3A%22539b3097dd899956e69ceb156c878aa7%22%7D&xxc=taobaoSearch

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives